// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClSFCeBojgBoHrxx9yp2mg0fZCy1pmGAU',
    appId: '1:954368708344:web:573d7f73d48bf85716f50d',
    messagingSenderId: '954368708344',
    projectId: 'drivermobileapp-570e5',
    authDomain: 'drivermobileapp-570e5.firebaseapp.com',
    storageBucket: 'drivermobileapp-570e5.firebasestorage.app',
    measurementId: 'G-DRL6FX334E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw0mlMVpEqkufGjuhEwjm8C_kwHtGbQlA',
    appId: '1:954368708344:android:3c124755f01e48db16f50d',
    messagingSenderId: '954368708344',
    projectId: 'drivermobileapp-570e5',
    storageBucket: 'drivermobileapp-570e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQW-o3tgA2C7yLUgPfO88mzNf_2NwccxI',
    appId: '1:954368708344:ios:6512b87f353e70f716f50d',
    messagingSenderId: '954368708344',
    projectId: 'drivermobileapp-570e5',
    storageBucket: 'drivermobileapp-570e5.firebasestorage.app',
    iosBundleId: 'com.example.web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQW-o3tgA2C7yLUgPfO88mzNf_2NwccxI',
    appId: '1:954368708344:ios:6512b87f353e70f716f50d',
    messagingSenderId: '954368708344',
    projectId: 'drivermobileapp-570e5',
    storageBucket: 'drivermobileapp-570e5.firebasestorage.app',
    iosBundleId: 'com.example.web',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClSFCeBojgBoHrxx9yp2mg0fZCy1pmGAU',
    appId: '1:954368708344:web:9ce496cedbb745b216f50d',
    messagingSenderId: '954368708344',
    projectId: 'drivermobileapp-570e5',
    authDomain: 'drivermobileapp-570e5.firebaseapp.com',
    storageBucket: 'drivermobileapp-570e5.firebasestorage.app',
    measurementId: 'G-FVZ8WBW1GE',
  );
}
